parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'


    Aa\AkeneoDataLoader\Api\Credentials:
        arguments:
            - '%env(AKENEO_API_HOST)%'
            - '%env(AKENEO_API_CLIENT_ID)%'
            - '%env(AKENEO_API_SECRET)%'
            - '%env(AKENEO_API_USER)%'
            - '%env(AKENEO_API_PASSWORD)%'

    Aa\AkeneoDataLoader\Connector\Configuration:
        arguments:
            - '%kernel.project_dir%/import/'
            - 100

    Aa\AkeneoFixtureLoader\FixtureLoaderFactory:
        arguments:
            - '@Aa\AkeneoDataLoader\Connector\Configuration'

    Aa\AkeneoFixtureLoader\FixtureLoader:
        factory: 'Aa\AkeneoFixtureLoader\FixtureLoaderFactory:createByCredentials'
        arguments:
            - '@Aa\AkeneoDataLoader\Api\Credentials'
